workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: Ryan ID
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_connect # Assumes you created this group in Codemagic UI with Issuer ID, Key ID, and Private Key
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_ID: "com.delagarza.scout" # Hardcoded ID
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup Identity and Build
        script: |
          set -e # Stop script immediately if any command fails
          
          echo "--- STEP 1: INITIALIZE KEYCHAIN (IN CONTEXT) ---"
          # We initialize the keychain in THIS shell so the session persists
          keychain initialize
          
          echo "--- STEP 2: ADD APPLE INTERMEDIATE CERT ---"
          # A common cause of "Cannot Save" errors is a missing WWDR certificate.
          # We manually fetch and install it to be safe.
          curl -o AppleWWDRCAG3.cer https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer
          keychain add-certificates AppleWWDRCAG3.cer

          echo "--- STEP 3: CREATE IDENTITY ---"
          APP_ID="com.delagarza.scout"
          
          # Now we create the certs. Because we are in the same shell as Step 1,
          # it has access to the unlocked keychain to save the private key.
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create
            
          echo "--- STEP 4: INSTALL DEPENDENCIES ---"
          flutter pub get
          find . -name "Podfile" -execdir pod install \;

          echo "--- STEP 5: BUILD IPA ---"
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --dart-define=API_KEY=$GEMINI_API_KEY
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups
          - "Internal Testers"
