workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: Ryan ID
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_connect # Assumes you created this group in Codemagic UI with Issuer ID, Key ID, and Private Key
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_ID: "com.delagarza.scout" # Hardcoded ID
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize Keychain (CRITICAL)
        script: |
          # This creates the local "wallet" to hold the private keys.
          # Without this, certificate creation fails instantly.
          keychain initialize

      - name: Clean Up and Create Identity
        script: |
          APP_ID="com.delagarza.scout"
          
          echo "--- STEP 1: REMOVE STALE PROFILES ---"
          # List all profiles to a file (fixing the invalid --filter argument)
          app-store-connect profiles list > profiles_dump.txt
          
          # Manually find profiles for our App ID and delete them
          grep "$APP_ID" profiles_dump.txt | awk '{print $1}' | while read -r PROF_ID; do
            echo "Deleting Profile: $PROF_ID"
            app-store-connect profiles delete --id "$PROF_ID" || echo "Checking next..."
          done

          echo "--- STEP 2: REMOVE STALE CERTS ---"
          # List all certs
          app-store-connect certificates list > certs_dump.txt
          
          # Delete any Distribution certs found to force a new one
          grep "Distribution" certs_dump.txt | awk '{print $1}' | while read -r CERT_ID; do
            echo "Deleting Cert: $CERT_ID"
            app-store-connect certificates delete --id "$CERT_ID" || echo "Checking next..."
          done

          echo "--- STEP 3: CREATE NEW IDENTITY ---"
          # Now that Keychain is active and old data is gone, create fresh.
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Install Dependencies
        script: |
          flutter packages get
          find . -name "Podfile" -execdir pod install \;

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --dart-define=API_KEY=$GEMINI_API_KEY
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups
          - "Internal Testers"
