workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_connect
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.delagarza.scout"
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.delagarza.scout
    
    scripts:
      - name: Set up iOS platform
        script: |
          # Generate iOS platform files
          flutter create --platforms=ios --org com.delagarza --project-name scout .
          
          # Update iOS deployment target to 14.0
          sed -i '' 's/platform :ios, '\''[0-9.]*'\''/platform :ios, '\''14.0'\''/' ios/Podfile
          
          # Also update in Xcode project
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' ios/Runner.xcodeproj/project.pbxproj
          
          # Remove hardcoded provisioning profile specifiers
          sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = 3ZB62C422U;/g' ios/Runner.xcodeproj/project.pbxproj
          
          # Create Info.plist directly
          cat > ios/Runner/Info.plist << 'INFOPLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>CFBundleDevelopmentRegion</key>
          	<string>$(DEVELOPMENT_LANGUAGE)</string>
          	<key>CFBundleDisplayName</key>
          	<string>Amble</string>
          	<key>CFBundleExecutable</key>
          	<string>$(EXECUTABLE_NAME)</string>
          	<key>CFBundleIdentifier</key>
          	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
          	<key>CFBundleInfoDictionaryVersion</key>
          	<string>6.0</string>
          	<key>CFBundleName</key>
          	<string>scout</string>
          	<key>CFBundlePackageType</key>
          	<string>APPL</string>
          	<key>CFBundleShortVersionString</key>
          	<string>$(FLUTTER_BUILD_NAME)</string>
          	<key>CFBundleSignature</key>
          	<string>????</string>
          	<key>CFBundleVersion</key>
          	<string>$(FLUTTER_BUILD_NUMBER)</string>
          	<key>LSRequiresIPhoneOS</key>
          	<true/>
          	<key>UILaunchStoryboardName</key>
          	<string>LaunchScreen</string>
          	<key>UIMainStoryboardFile</key>
          	<string>Main</string>
          	<key>UISupportedInterfaceOrientations</key>
          	<array>
          		<string>UIInterfaceOrientationPortrait</string>
          		<string>UIInterfaceOrientationLandscapeLeft</string>
          		<string>UIInterfaceOrientationLandscapeRight</string>
          	</array>
          	<key>UISupportedInterfaceOrientations~ipad</key>
          	<array>
          		<string>UIInterfaceOrientationPortrait</string>
          		<string>UIInterfaceOrientationPortraitUpsideDown</string>
          		<string>UIInterfaceOrientationLandscapeLeft</string>
          		<string>UIInterfaceOrientationLandscapeRight</string>
          	</array>
          	<key>UIViewControllerBasedStatusBarAppearance</key>
          	<false/>
          	<key>CADisableMinimumFrameDurationOnPhone</key>
          	<true/>
          	<key>UIApplicationSupportsIndirectInputEvents</key>
          	<true/>
          </dict>
          </plist>
          INFOPLIST
          
          # Get dependencies
          flutter pub get
      
      - name: Set up code signing
        script: |
          # Apply profiles
          xcode-project use-profiles
          
          # Debug: Check what profiles are available
          echo "=== Provisioning profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # Get the actual profile that was installed
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | head -1)
          
          if [ -n "$PROFILE_PATH" ]; then
            echo "Using profile: $PROFILE_PATH"
            # Get profile name
            PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print :Name" /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
            echo "Profile name: $PROFILE_NAME"
          fi
      
      - name: Build iOS app
        script: |
          # Let Flutter handle everything - it should use the profiles installed by xcode-project use-profiles
          flutter build ipa --release
          
          # Verify IPA was created
          echo "=== Checking for IPA file ==="
          if [ -d "build/ios/ipa" ]; then
            ls -lh build/ios/ipa/
          else
            echo "ERROR: IPA directory not created"
            echo "Checking archive..."
            ls -lh build/ios/archive/ || echo "No archive either!"
            exit 1
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - ryan.e.delagarza@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true